#!/usr/bin/env bash
# build.sh — assemble per-platform plugins from the canonical core/ content.
#
#   core/skills/<slug>/   → copied verbatim into every plugin's skills/
#   core/agents/<name>.body.md + core/agents/agents.json
#                         → rendered with per-platform frontmatter into
#                           plugins/{opencode,agy,claude}/agents/<name>.md
#   core/commands/*.md    → plugins/opencode/commands/*.md (as-is)
#                           plugins/agy/commands/*.toml  (converted)
#
# Manifests (plugin.json), READMEs, and install.sh are authored directly in
# plugins/<platform>/ and are never touched by this script.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CORE="$REPO_ROOT/core"
META="$CORE/agents/agents.json"
PLUGINS="$REPO_ROOT/plugins"
PLATFORMS_SKILLS=(agy codex claude opencode)
PLATFORMS_AGENTS=(agy claude opencode)
PLATFORMS_COMMANDS=(agy opencode)

die() { echo "build.sh: ERROR: $*" >&2; exit 1; }

jq -e . "$META" >/dev/null 2>&1 || die "agents.json is not valid JSON"

render_description() { # $1 = agent name; emits folded YAML description
  local desc
  desc="$(jq -r '.agents["'"$1"'"].description' "$META")"
  printf 'description: >-\n  %s\n' "$desc"
}

build_skills() {
  for plat in "${PLATFORMS_SKILLS[@]}"; do
    local dir="$PLUGINS/$plat/skills"
    rm -rf "$dir"
    mkdir -p "$dir"
    cp -r "$CORE/skills/evolve"        "$dir/evolve"
    cp -r "$CORE/skills/state-sync"    "$dir/state-sync"
    cp -r "$CORE/skills/run-notesmd-cli" "$dir/run-notesmd-cli"
    rm -rf "$dir/evolve/scripts/__pycache__"
  done
  echo "  skills -> ${PLATFORMS_SKILLS[*]}"
}

build_agents() {
  local agent
  for plat in "${PLATFORMS_AGENTS[@]}"; do
    local dir="$PLUGINS/$plat/agents"
    rm -rf "$dir"
    mkdir -p "$dir"
    for agent in evolver observer; do
      local body="$CORE/agents/$agent.body.md"
      local out="$dir/$agent.md"
      [[ -f "$body" ]] || die "missing body: $body"
      {
        printf -- '---\nname: %s\n' "$agent"
        render_description "$agent"
        case "$plat" in
          opencode)
            printf 'mode: subagent\n'
            printf 'tools:\n'
            jq -r '.agents["'"$agent"'"].tools.opencode
                   | to_entries | map("  \(.key): \(if .value then "true" else "false" end)") | .[]' "$META"
            ;;
          agy)
            printf 'tools: %s\n' "$(jq -r '.agents["'"$agent"'"].tools.agy | "[" + (map(tostring) | join(", ")) + "]"' "$META")"
            ;;
          claude)
            printf 'tools: %s\n' "$(jq -r '.agents["'"$agent"'"].tools.claude | join(", ")' "$META")"
            ;;
        esac
        printf -- '---\n\n'
        cat "$body"
      } > "$out"
    done
  done
  echo "  agents -> ${PLATFORMS_AGENTS[*]}"
}

build_commands() {
  # OpenCode: markdown with YAML frontmatter (pass-through)
  rm -rf "$PLUGINS/opencode/commands"
  mkdir -p "$PLUGINS/opencode/commands"
  cp "$CORE/commands/"*.md "$PLUGINS/opencode/commands/"

  # agy (Antigravity): Gemini-style TOML commands
  rm -rf "$PLUGINS/agy/commands"
  mkdir -p "$PLUGINS/agy/commands"
  for src in "$CORE/commands/"*.md; do
    local name
    name="$(basename "$src" .md)"
    local desc
    desc="$(sed -n 's/^description: //p' "$src" | head -1)"
    local prompt
    prompt="$(awk 'BEGIN{c=0} /^---$/{c++; next} c==2 {print}' "$src")"
    {
      printf '# Generated by build.sh from core/commands/%s.md\n' "$name"
      printf 'name = "%s"\n' "$name"
      printf 'description = "%s"\n' "$desc"
      printf 'prompt = """\n%s"""\n' "$prompt"
    } > "$PLUGINS/agy/commands/$name.toml"
  done
  echo "  commands -> opencode, agy (toml)"
}

echo "Assembling evolution-harness plugins from core/ ..."
build_skills
build_agents
build_commands
echo "Done."